import "./globals.css";

export const metadata = {
  title: "Hangul",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-black">
        {children}
      </body>
    </html>
  );
}
