import "./globals.css";

export const metadata = {
  title: "Hangul",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex justify-center">
        <div className="w-[60%]">
          {children}
        </div>
      </body>
    </html>
  );
}
